#!/usr/bin/env bash

set -euo pipefail

main() (
  cursor_url=$(local-config cursor.linux_x86)
  cursor_url=${cursor_url:-$(home-config cursor.linux-x86)}

  apt_install=$(
    (
      home-config  docker.install || true;
      local-config docker.install || true;
    ) | sort | uniq | xargs
  )

  config_mk=$(mktemp $TMPDIR/XXXXXXXX)

  cat <<... > "$config_mk"
CURSOR-APP-URL ?= $cursor_url
APT-INSTALL := $apt_install
...

  echo "$config_mk"
)

home_config=$HOME/.secursor/config
local_config=$PWD/.secursor/config

home-config() (
  if [[ -f $home_config ]]; then
    git config -f "$home_config" "$1" || true
  fi
)

local-config() (
  if [[ -f $local_config ]]; then
    git config -f "$local_config" "$1" || true
  fi
)

die() {
  printf '%s\n' "$@" >&2
  exit 1
}

main "$@"
